# Site settings
title: "Amos Adekunle Ezekiel"
description: "Portfolio Site"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Amos Adekunle Ezekie"
resume_title:                   "Senior Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tobideveloper@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+2349066504804"
resume_contact_address:         "20 Oduduwa Street Ikeja Gra, Lagos, Nigeria"

resume_header_contact_info:     "20 Oduduwa Street Ikeja Gra, Lagos, Nigeria • +2349066504804 • tobideveloper@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Interested in buidling software that improves standard of living/p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/tobiamos"
  resume_twitter_url:           "http://twitter.com/tobi"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/amos-adekunle-279090159/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://iamtobi.me"
  resume_medium_url:            "https://medium.com/@tobideveloper"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
